version: '3.8'

services:
  wolt-checker-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./src/db:/app/db
    restart: unless-stopped
    command: npm start

  wolt-checker-notify:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./src/db:/app/db
    restart: unless-stopped
    command: npm run notify
    depends_on:
      - wolt-checker-bot
